### ISSUE TITLE
Add exception

### ISSUE THREAD

**Issue by cajeiri** [DuckieTV/SceneNameExceptions#5]
Torrents for The Late Show with Stephen Colbert are aptly named just Stephen Colbert. Searching for the full name of the show doesn't bring up any (new) results in most of the default sources.

Edit: On a separate note, the uploaders seem to use yyyy mm dd instead of season + episode. Any chance anybody's gone to the trouble of making the equivalent of a thexem.de cache for this show?

**Comment by garfield69** [comment]
The sceneNameExceptions table was updated 5 years ago to make Dtv search for Stephen Colbert instead of the series full name.
And the SceneDateExceptions table was updated 3 years ago to make Dtv use yyyy mm dd instead of season/episode.
So if your Dtv is not using these exceptions then you have a problem with your Dtv.
If you want help diagnosis that problem then raise a ticket on https://github.com/SchizoDuckie/DuckieTV

**Comment by cajeiri** [comment]
Update: I was running a nightly from late February. No idea what was going on, but restarting the program made it search in the proper manner. Will still update to today's Windows nightly to be on the safe side. Probably a rare exception/bug that's a non-issue.
